function [ys_, params, info] = steadystate(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(4)=1;
    ys_(10)=1;
    ys_(11)=1;
    ys_(12)=1;
    ys_(20)=1;
    ys_(15)=(params(10)-1)/params(10)/(1-params(12));
    ys_(6)=1/params(2);
    ys_(3)=1;
    ys_(9)=1/ys_(6);
    ys_(7)=ys_(6);
    ys_(5)=(ys_(15)*(1-params(1)))^(1/(params(6)+params(1)*(1-params(6))+params(7)));
    ys_(1)=ys_(4)*ys_(5)^(1-params(1));
    ys_(2)=ys_(1)^params(6)*ys_(5)^params(7);
    ys_(8)=ys_(1);
    money_growth=0;
    money_growth_ann=0;
    ys_(28)=0;
    ys_(13)=ys_(15)*ys_(8)*ys_(1)^(-params(6))/(1-params(2)*params(11)*ys_(3)^(params(10)/(1-params(1))));
    ys_(14)=ys_(8)*ys_(1)^(-params(6))/(1-params(2)*params(11)*ys_(3)^(params(10)-1));
    ys_(22)=log(ys_(8));
    ys_(23)=log(ys_(2));
    ys_(24)=log(ys_(5));
    ys_(18)=4*log(ys_(3));
    ys_(17)=4*log(ys_(6));
    ys_(19)=4*log(ys_(7));
    ys_(16)=ys_(8)/ys_(6)^params(13);
    ys_(21)=log(ys_(20)*ys_(16));
    ys_(25)=log(ys_(20));
    ys_(26)=0;
    ys_(27)=0;
    % Auxiliary equations
end
